name: Idea Test Suite
on: ["push", "pull_request"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install dependencies
        run: yarn
      - name: Building Code
        run: yarn build
      - name: Run Tests
        run: yarn report
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          files: coverage/lcov.info packages/idea-rust/coverage/lcov.info
          format: lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
